FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY *.sln ./

COPY src/AuthService.Api/*.csproj ./src/AuthService.Api/
COPY src/AuthService.Domain/*.csproj ./src/AuthService.Domain/
COPY src/AuthService.Application/*.csproj ./src/AuthService.Application/
COPY src/AuthService.Persistence/*.csproj ./src/AuthService.Persistence/

RUN dotnet restore src/AuthService.Api/AuthService.Api.csproj

COPY . .

WORKDIR /app/src/AuthService.Api
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 10000

ENV ASPNETCORE_URLS=http://+:10000

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "AuthService.Api.dll"]